version: '3.7'

services:
  nginx:
    image: cr.yandex/crpkv40doqi2snrfmq1e/tridva-nginx
    ports:
      - '80:80'
      - '443:443'
    restart: always
    volumes:
      - /etc/ssl/certs/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - /etc/ssl/private/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
    depends_on:
      - backend

  backend:
    image: cr.yandex/crpkv40doqi2snrfmq1e/tridva-api
    restart: always
