version: '3.7'

services:
  nginx:
    image: {{env.NGINX_IMAGE}}
    ports:
      - '80:80'
      - '443:443'
    restart: always
    environment:
      NGINX_CERT: {{env.NGINX_CERT}}
      NGINX_CERT_KEY: {{env.NGINX_CERT_KEY}}
    depends_on:
      - backend

  backend:
    image: {{env.BACKEND_IMAGE}}
    restart: always
