version: '3.7'

services:
  nginx:
    image: cr.yandex/crpkv40doqi2snrfmq1e/tridva-nginx
    ports:
      - '80:80'
      - '443:443'
    restart: always
    environment:
      NGINX_CERT: /etc/ssl/certs/nginx-selfsigned.crt
      NGINX_CERT_KEY: /etc/ssl/private/nginx-selfsigned.key
    depends_on:
      - backend

  backend:
    image: cr.yandex/crpkv40doqi2snrfmq1e/tridva-api
    restart: always
